all:
  vars:
    ansible_connection : httpapi
    # Use network_cli for SSH-based connections, instead of httpapi)
    ansible_network_os : eos
    ansible_become : yes
    ansible_become_method : enable 
    ansible_python_interpreter : /usr/bin/python3
    ansible_user : arista
    ansible_password : aristay8ns
    ansible_httpapi_use_ssl : True
    ansible_httpapi_validate_certs : False
    #ansible_httpapi_port : 443 ( only needed if https port is not 443)
  children:
    DC1:
      children:
        leafs_DC1:
          hosts:
            leaf[1:4]-DC1:
            borderleaf[1:2]-DC1: 
        spines_DC1:
          hosts:
            spine[1:3]-DC1:
        
    DC2:
      children:
        leafs_DC2:
          hosts:
            leaf[1:4]-DC2:
            borderleaf[1:2]-DC2: 
        spines_DC2:
          hosts:
            spine[1:3]-DC2:
    DCI_SW:
      hosts:
        DCI:
      
     