---
- name: "PLAY 1 - DEPLOYING SNMP CONFIGURATIONS ON EOS"
  hosts: leaf1-DC1
  # connection: "ansible.netcommon.network_cli"
  gather_facts: false


  vars:
    # vlan_id:
    #   - 40
    #   - 41
    #   - 43
    #   - 44
    #   - 45
    vlans_to_rem:
      - 40
      - 41
      - 42

  vars_files: './vars/vlan_vars.yml' 
  tasks:
  - name: CONFIGURE a vlan using eos_config module
    arista.eos.eos_config:
      lines:
        - vlan {{item}}
        - name DATA_VLAN
    loop: "{{vlan_id}}"
    vars:
      vlan_id:
        - 46
        - 47

  - name: Remove vlans using eos_config module
    arista.eos.eos_config:
      lines:
        - no vlan {{item}}
    loop: "{{vlans_to_rem}}"